[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; style-src 'self, https://fonts.googleapis.com/css?family=Roboto+Mono'; img-src 'self'"
    Expect-CT = "enforce, max-age=30"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "autoplay 'none'; camera 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; midi 'none'; payment 'none'; vr 'none';"
    X-DNS-Prefetch-Control = "off"
    X-Permitted-Cross-Domain-Policies = "none"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Download-Options = "noopen"
    X-Content-Type-Options = "nosniff"
    Server = "Secret"