[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'none'; font-src data: 'self' fonts.gstatic.com; style-src 'self' fonts.googleapis.com; img-src data: 'self'; frame-src https://docs.google.com/;"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "autoplay 'none'; camera 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; midi 'none'; payment 'none'; vr 'none';"
    X-DNS-Prefetch-Control = "off"
    X-Permitted-Cross-Domain-Policies = "none"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Download-Options = "noopen"
    X-Content-Type-Options = "nosniff"
    Server = "Secret"
    Expect-CT = "enforce, max-age=30"